config = {
    'repo2team': {
        'prototype': '<Monorepo-java>',
        'sfxinternalgo': '<Monorepo-go>',
        'cloud-metric-syncer': 'CK',
        'cloudwatch-proxy': 'CK',
        'muting': 'CK',
        'notification': 'CK',
        'msteams-connector-page': 'CK',
        'lambda-layer-versions': 'CK',
        'cloudwatch-event-forwarder': 'CK',
        'aws-log-collector': 'CK',
        'enhganced-rds-monitoring': 'CK',
        'fluent-bit-plugin': 'CK',
        'entity-etl': 'CK',
        'grafana-signalfx-datasource': 'CK',
        'sfxinternalgo': 'Gandalf',
        'smartsampler': 'Gandalf',
        'signalfx-agent': 'Instrumentals, Rotel',
        'splunk-otel-java': 'Instrumentals',
        'splunk-otel-java-lambda': 'Instrumentals',
        'splunk-otel-python': 'Instrumentals',
        'splunk-otel-js': 'Instrumentals',
        'splunk-otel-dotnet': 'Instrumentals',
        'splunk-browser-otel-js': 'Instrumentals',
        'signalfx-nodejs-tracing': 'Instrumentals',
        'signalfx-dotnet-tracing': 'Instrumentals',
        'signalfx-java-tracing': 'Instrumentals',
        'lambda-nodejs': 'Instrumentals, CK',
        'lambda-python': 'Instrumentals, CK',
        'lambda-ruby': 'Instrumentals, CK',
        'lambda-csharp': 'Instrumentals, CK',
        'lambda-java': 'Instrumentals, CK',
        'lambda-go': 'Instrumentals, CK',
        'mts-category-generator': 'Rotel',
    },
    'keyword2team': {
        'aws': 'CK',
        'gcp': 'CK',
        'azure': 'CK',
        'lambda': 'CK',
        'agent': 'Rotel',
        'otel': 'Instrumentals',
        'opentelemetry': 'Instrumentals',
        'jaeger': 'Instrumentals',
        'rum': 'Instrumentals',
        'xray': 'Instrumentals',
        'trace': 'Instrumentals',
        'traces': 'Instrumentals',
        'tracing': 'Instrumentals',
        'apm': 'Instrumentals',
        'events': 'Instrumentals',
        'instrumentation': 'Instrumentals',
        'd3': '<UI>',
        'swagger': '<UI>',
        'signalview': '<UI>',
        'wizard': '<UI>',
        'angular': '<UI>',
        'bower': '<UI>',
        'icon': '<UI>',
        'docs': '<DOCS>',
        'test': '<QA>',
        'puppet': '<Infra>',
        'kafka': '<Infra>',
        'cassandrs': '<Infra>',
        'log': 'Instrumentals',
        'pulsar': '<Infra>',
        'ssh': '<Infra>',
        'docker': '<Infra>',
        'redis': '<Infra>',
        'zipkin': '<Infra>',
        'elasticsearch': '<Infra>',

    },

}